---

- name: "Install packages needed for proxy server"
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - haproxy

- name: "Create haproxy config file from template"
  template: src=haproxy.conf.j2 dest=/etc/haproxy/haproxy.cfg owner=root group=root mode=0644
  notify: restart haproxy