---

- name: "Install packages needed for dns server"
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - dnsmasq

- name: "Create dnsmasq config file from template"
  template: src=dnsmasq.conf.j2 dest=/etc/dnsmasq.conf owner=root group=root mode=0644
  notify: restart dnsmasq