---
- hosts: all
  become: true
  become_user: root
  roles:
    - common

- hosts: proxy
  become: true
  become_user: root
  roles: 
    - proxy

- hosts: dns
  become: true
  become_user: root
  roles:
    - dns

